/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pe.edu.pucp.linelight.view;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import javax.swing.table.DefaultTableModel;
import pe.edu.pucp.linelight.controller.DistritoController;
import pe.edu.pucp.linelight.controller.TipoViaController;
import pe.edu.pucp.linelight.controller.semaforoController;
import pe.edu.pucp.linelight.controller.ViaController;
import pe.edu.pucp.linelight.model.Distrito;
import pe.edu.pucp.linelight.model.Semaforo;
import pe.edu.pucp.linelight.model.Tipovia;
import pe.edu.pucp.linelight.model.Via;
import pe.edu.pucp.linelight.util.ValidationUtil;

/**
 *
 * 
 * @author USER
 */
public class buscarSemaforo extends javax.swing.JPanel {

    /**
     * Creates new form buscarSemaforo
     */
    public buscarSemaforo() {
        initComponents();
        this.setBackground(new java.awt.Color(240, 240, 240));
        ArrayList<Distrito> distritos = DistritoController.obtenerDistritos();
        for (int i = 0; i < distritos.size(); i++){
            cmbDistrito.addItem(distritos.get(i).getNombre());
        }
        ArrayList<Tipovia> tipos = TipoViaController.obtenerTipos();
        for (int i = 0; i < tipos.size(); i++){
            cmbTipoVia1.addItem(tipos.get(i).getDescripcion());
            cmbTipoVia2.addItem(tipos.get(i).getDescripcion());            
        }
        //Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        ArrayList<Via> vias = ViaController.obtenerVias();
        for (int i = 0; i < vias.size(); i++){
            cmbVia1.addItem(vias.get(i).getNombre());
            cmbVia2.addItem(vias.get(i).getNombre());            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbDistrito = new javax.swing.JComboBox();
        buscar_usuario_button = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cmbTipoVia1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cmbVia1 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        cmbTipoVia2 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        cmbVia2 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        txtIdentificador = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaSemaforo = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCoincidencia = new javax.swing.JTextField();
        buscar_usuario_button1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 647));
        setRequestFocusEnabled(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Criterios de Búsqueda Detallada"));
        jPanel3.setAlignmentX(0.0F);
        jPanel3.setAlignmentY(0.0F);

        jLabel3.setText("Distrito:");

        cmbDistrito.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione" }));
        cmbDistrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDistritoActionPerformed(evt);
            }
        });

        buscar_usuario_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buscar_opt.png"))); // NOI18N
        buscar_usuario_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_usuario_buttonActionPerformed(evt);
            }
        });

        jLabel5.setText("Tipo de vía1:");

        cmbTipoVia1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione" }));
        cmbTipoVia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoVia1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Vía Principal:");

        cmbVia1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione" }));
        cmbVia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbVia1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Tipo de vía2:");

        cmbTipoVia2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione" }));
        cmbTipoVia2.setAlignmentX(0.0F);
        cmbTipoVia2.setAlignmentY(0.0F);
        cmbTipoVia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoVia2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Vía Secundaria:");

        cmbVia2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione" }));

        jLabel1.setText("Identificador:");

        txtIdentificador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdentificadorActionPerformed(evt);
            }
        });
        txtIdentificador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdentificadorKeyTyped(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("(*)");

        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("(*)");

        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("(*) Datos no considerados en búsqueda");

        jLabel12.setText("Estado:");

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Habilitado", "Deshabilitado" }));
        cmbEstado.setAlignmentX(0.0F);
        cmbEstado.setAlignmentY(0.0F);
        cmbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbTipoVia1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbTipoVia2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(275, 275, 275)
                                        .addComponent(jLabel2))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(178, 178, 178)
                                        .addComponent(jLabel15))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbVia1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbVia2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addComponent(buscar_usuario_button)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cmbDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbVia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(jLabel4))
                    .addComponent(buscar_usuario_button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jLabel15))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel11)))
                        .addComponent(cmbVia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbTipoVia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cmbTipoVia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados"));

        tablaSemaforo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Semaforo", "Distrito", "Vía Principal", "Vía Secundaria", "Tiempo Verde", "Tiempo Rojo", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaSemaforo.setToolTipText("");
        jScrollPane2.setViewportView(tablaSemaforo);
        tablaSemaforo.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Criterios de Búsqueda Rápida"));

        jLabel9.setText("Coincidencia rápida por vía:");
        jLabel9.setToolTipText("");

        buscar_usuario_button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buscar_opt.png"))); // NOI18N
        buscar_usuario_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_usuario_button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(33, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(37, 37, 37)
                        .addComponent(txtCoincidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(buscar_usuario_button1)
                .addGap(42, 42, 42))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtCoincidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buscar_usuario_button1)
                .addContainerGap())
        );

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editar_opt.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/agregar_opt.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        NuevoSemaforo nuevo= new NuevoSemaforo();
        nuevo.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buscar_usuario_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_usuario_button1ActionPerformed
        // TODO add your handling code here:
        
        String coincidencia = txtCoincidencia.getText();
            if (coincidencia.isEmpty()) coincidencia = null;
        ArrayList<Semaforo> semaforoCriteria = semaforoController.obtenerSemaforosCoincidencia(coincidencia);
        DefaultTableModel tbm= new DefaultTableModel();
        String [] titulos={"Id Semaforo","Distrito","Via Principal","Via Secundaria","Tiempo Verde", "Tiempo Rojo", "Estado"};
        tbm.setColumnIdentifiers(titulos); tablaSemaforo.setModel(tbm);
        for (int i=0;i<semaforoCriteria.size();i++){ 
            
            String datos[]=new String[7];
            datos[0] = Long.toString(semaforoCriteria.get(i).getId().getIdSemaforo());            
            datos[1] = semaforoController.obtenerDistritoxNombreVia(semaforoCriteria.get(i).getVia1());            
            datos[2] = (semaforoCriteria.get(i).getVia1());
            datos[3] = (semaforoCriteria.get(i).getVia2());
            datos[4] = Integer.toString(semaforoCriteria.get(i).getTverde());
            datos[5] = Integer.toString(semaforoCriteria.get(i).getTrojo());
            datos[6] = (semaforoCriteria.get(i).getEstado() == true ? "Habilitado" : "Deshabilitado");            
            tbm.addRow(datos);

        }
        tablaSemaforo.setModel(tbm);
    }//GEN-LAST:event_buscar_usuario_button1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int numFila = tablaSemaforo.getSelectedRow();
        if (numFila >= 0){
            String idSemaforo = (String) tablaSemaforo.getValueAt(numFila,0);
            String nombreDistrito = (String) tablaSemaforo.getValueAt(numFila,1);
            String via1 = (String) tablaSemaforo.getValueAt(numFila,2);
            String via2 = (String) tablaSemaforo.getValueAt(numFila,3);
            String tiempoVerde = (String) tablaSemaforo.getValueAt(numFila,4);
            String tiempoRojo = (String) tablaSemaforo.getValueAt(numFila,5);
            String estado = (String) tablaSemaforo.getValueAt(numFila,6);
            
            editarSemáforo editar= new editarSemáforo(idSemaforo, nombreDistrito, via1, via2, tiempoVerde, tiempoRojo, estado);
            editar.setVisible(true);  
        }else{
            int seleccion = JOptionPane.showOptionDialog(
                    buscarSemaforo.this, // Componente padre
                    "Debe seleccionar una fila", //Mensaje
                    "Mensaje de sugerencia", // Título
                    JOptionPane.OK_OPTION,
                    JOptionPane.OK_OPTION,
                    null,    // null para icono por defecto.
                    new Object[] { "Aceptar"},    // null para YES, NO y CANCEL
                    "Aceptar");
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEstadoActionPerformed

    private void txtIdentificadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentificadorKeyTyped
        // TODO add your handling code here:
        ValidationUtil.validateNumTam(txtIdentificador.getText(), 15, evt);
    }//GEN-LAST:event_txtIdentificadorKeyTyped

    private void cmbTipoVia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoVia2ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        cmbVia2.removeAllItems();
        cmbVia2.addItem("Seleccione");
        if (cmbTipoVia2.getSelectedIndex() == 0){
            if (cmbDistrito.getSelectedIndex() != 0){
                ArrayList<Via> viasDistrinto = ViaController.obtenerVias(DistritoController.obteneridDistrito((String)cmbDistrito.getSelectedItem()));
                for (int i = 0; i < viasDistrinto.size(); i++){
                    cmbVia2.addItem(viasDistrinto.get(i).getNombre());
                }
            }else{
                ArrayList<Via> vias = ViaController.obtenerVias();
                for (int i = 0; i < vias.size(); i++)
                cmbVia1.addItem(vias.get(i).getNombre());
            }
        }if (cmbTipoVia2.getSelectedIndex() != 0 && cmbDistrito.getSelectedIndex() != 0){
            //Cargo las vias con el distrito seleccionado y el tipo de via
            int idDistrito = DistritoController.obteneridDistrito((String)cmbDistrito.getSelectedItem());
            int idTipoVia = TipoViaController.obteneridTipo((String)cmbTipoVia2.getSelectedItem());
            ArrayList<Via> vias =  ViaController.obtenerViasxIdxDistrito(idTipoVia, idDistrito);
            for (int i = 0; i < vias.size(); i++){
                cmbVia2.addItem(vias.get(i).getNombre());
            }
        }if (cmbTipoVia2.getSelectedIndex() != 0 && cmbDistrito.getSelectedIndex() == 0){
            //Cargo las vias con el distrito seleccionado y el tipo de via
            int idTipoVia = TipoViaController.obteneridTipo((String)cmbTipoVia2.getSelectedItem());
            ArrayList<Via> vias =  ViaController.obtenerViasxId(idTipoVia);
            for (int i = 0; i < vias.size(); i++){
                cmbVia2.addItem(vias.get(i).getNombre());
            }
        }
    }//GEN-LAST:event_cmbTipoVia2ActionPerformed

    private void cmbVia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbVia1ActionPerformed

    }//GEN-LAST:event_cmbVia1ActionPerformed

    private void cmbTipoVia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoVia1ActionPerformed
        // TODO add your handling code here:
        cmbVia1.removeAllItems();
        cmbVia1.addItem("Seleccione");
        if (cmbTipoVia1.getSelectedIndex() == 0){
            if (cmbDistrito.getSelectedIndex() != 0){
                ArrayList<Via> viasDistrinto = ViaController.obtenerVias(DistritoController.obteneridDistrito((String)cmbDistrito.getSelectedItem()));
                for (int i = 0; i < viasDistrinto.size(); i++){
                    cmbVia1.addItem(viasDistrinto.get(i).getNombre());
                }
            }else{
                ArrayList<Via> vias = ViaController.obtenerVias();
                for (int i = 0; i < vias.size(); i++)
                cmbVia1.addItem(vias.get(i).getNombre());

            }

        }if (cmbTipoVia1.getSelectedIndex() != 0 && cmbDistrito.getSelectedIndex() != 0){
            //Cargo las vias con el distrito seleccionado y el tipo de via
            int idDistrito = DistritoController.obteneridDistrito((String)cmbDistrito.getSelectedItem());
            int idTipoVia = TipoViaController.obteneridTipo((String)cmbTipoVia1.getSelectedItem());
            ArrayList<Via> vias =  ViaController.obtenerViasxIdxDistrito(idTipoVia, idDistrito);
            for (int i = 0; i < vias.size(); i++){
                cmbVia1.addItem(vias.get(i).getNombre());
            }
        }if (cmbTipoVia1.getSelectedIndex() != 0 && cmbDistrito.getSelectedIndex() == 0){
            //Cargo las vias con el distrito seleccionado y el tipo de via
            int idTipoVia = TipoViaController.obteneridTipo((String)cmbTipoVia1.getSelectedItem());
            ArrayList<Via> vias =  ViaController.obtenerViasxId(idTipoVia);
            for (int i = 0; i < vias.size(); i++){
                cmbVia1.addItem(vias.get(i).getNombre());
            }
        }
    }//GEN-LAST:event_cmbTipoVia1ActionPerformed

    private void buscar_usuario_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_usuario_buttonActionPerformed
        // TODO add your handling code here:

        String estado = (String)cmbEstado.getSelectedItem();
        if (estado.equals("Seleccione")) estado = null;
        String identificador = txtIdentificador.getText();
        if (identificador.isEmpty()) identificador = null;
        String distrito = (String)cmbDistrito.getSelectedItem();
        if (distrito.equals("Seleccione") ) distrito = null;
        String tipoVia1 = (String)cmbTipoVia1.getSelectedItem();
        if (tipoVia1.equals("Seleccione") ) tipoVia1 = null;
        String tipoVia2 = (String)cmbTipoVia2.getSelectedItem();
        if (tipoVia2.equals("Seleccione") ) tipoVia2 = null;
        String via1     = (String)cmbVia1.getSelectedItem();
        if (via1.equals("Seleccione") ) via1 = null;
        String via2     = (String)cmbVia2.getSelectedItem();
        if (via2.equals("Seleccione") ) via2 = null;
        ArrayList<Semaforo> semaforoCriteria = semaforoController.obtenerSemaforosCriteria(estado,identificador, distrito, tipoVia1, tipoVia2, via1, via2);
        DefaultTableModel tbm= new DefaultTableModel();
        String [] titulos={"Id Semaforo","Distrito","Via Principal","Via Secundaria","Tiempo Verde", "Tiempo Rojo", "Estado"};
        tbm.setColumnIdentifiers(titulos); tablaSemaforo.setModel(tbm);
        for (int i=0;i<semaforoCriteria.size();i++){

            String datos[]=new String[7];
            datos[0] = Long.toString(semaforoCriteria.get(i).getId().getIdSemaforo());
            datos[1] = semaforoController.obtenerDistritoxNombreVia(semaforoCriteria.get(i).getVia1());
            datos[2] = (semaforoCriteria.get(i).getVia1());
            datos[3] = (semaforoCriteria.get(i).getVia2());
            datos[4] = Integer.toString(semaforoCriteria.get(i).getTverde());
            datos[5] = Integer.toString(semaforoCriteria.get(i).getTrojo());
            datos[6] = (semaforoCriteria.get(i).getEstado() == true ? "Habilitado" : "Deshabilitado");
            tbm.addRow(datos);

        }
        tablaSemaforo.setModel(tbm);
    }//GEN-LAST:event_buscar_usuario_buttonActionPerformed

    private void cmbDistritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDistritoActionPerformed
        // TODO add your handling code here:
        cmbVia1.removeAllItems();
        cmbVia2.removeAllItems();
        cmbVia1.addItem("Seleccione");
        cmbVia2.addItem("Seleccione");
        if (cmbDistrito.getSelectedIndex() == 0){

            cmbVia1.setSelectedIndex(0);
            cmbVia2.setSelectedIndex(0);
            ArrayList<Via> vias = ViaController.obtenerVias();
            for (int i = 0; i < vias.size(); i++){
                cmbVia1.addItem(vias.get(i).getNombre());
                cmbVia2.addItem(vias.get(i).getNombre());
            }
        }
        if (cmbDistrito.getSelectedIndex() != 0 && cmbTipoVia1.getSelectedIndex() == 0 && cmbTipoVia2.getSelectedIndex() == 0){

            ArrayList<Via> viasDistrinto = ViaController.obtenerVias(DistritoController.obteneridDistrito((String)cmbDistrito.getSelectedItem()));
            for (int i = 0; i < viasDistrinto.size(); i++){
                cmbVia1.addItem(viasDistrinto.get(i).getNombre());
                cmbVia2.addItem(viasDistrinto.get(i).getNombre());
            }
        }
        if (cmbTipoVia1.getSelectedIndex() != 0 && cmbDistrito.getSelectedIndex() != 0 && cmbTipoVia2.getSelectedIndex() == 0){
            int idDistrito = DistritoController.obteneridDistrito((String)cmbDistrito.getSelectedItem());
            int idTipoVia = TipoViaController.obteneridTipo((String)cmbTipoVia1.getSelectedItem());
            ArrayList<Via> vias =  ViaController.obtenerViasxIdxDistrito(idTipoVia, idDistrito);
            for (int i = 0; i < vias.size(); i++){
                cmbVia1.addItem(vias.get(i).getNombre());
            }
            ArrayList<Via> viasDistrinto = ViaController.obtenerVias(DistritoController.obteneridDistrito((String)cmbDistrito.getSelectedItem()));
            for (int i = 0; i < viasDistrinto.size(); i++){
                cmbVia2.addItem(viasDistrinto.get(i).getNombre());
            }
        }

        if (cmbTipoVia2.getSelectedIndex() != 0 && cmbDistrito.getSelectedIndex() != 0 && cmbTipoVia1.getSelectedIndex() == 0){
            int idDistrito = DistritoController.obteneridDistrito((String)cmbDistrito.getSelectedItem());
            int idTipoVia = TipoViaController.obteneridTipo((String)cmbTipoVia2.getSelectedItem());
            ArrayList<Via> vias =  ViaController.obtenerViasxIdxDistrito(idTipoVia, idDistrito);
            for (int i = 0; i < vias.size(); i++){
                cmbVia2.addItem(vias.get(i).getNombre());
            }
            ArrayList<Via> viasDistrinto = ViaController.obtenerVias(DistritoController.obteneridDistrito((String)cmbDistrito.getSelectedItem()));
            for (int i = 0; i < viasDistrinto.size(); i++){
                cmbVia1.addItem(viasDistrinto.get(i).getNombre());
            }
        }

        if (cmbTipoVia1.getSelectedIndex() != 0 && cmbDistrito.getSelectedIndex() != 0 && cmbTipoVia2.getSelectedIndex() != 0){
            int idDistrito = DistritoController.obteneridDistrito((String)cmbDistrito.getSelectedItem());
            int idTipoVia = TipoViaController.obteneridTipo((String)cmbTipoVia1.getSelectedItem());
            ArrayList<Via> vias =  ViaController.obtenerViasxIdxDistrito(idTipoVia, idDistrito);
            for (int i = 0; i < vias.size(); i++){
                cmbVia1.addItem(vias.get(i).getNombre());
            }
            idTipoVia = TipoViaController.obteneridTipo((String)cmbTipoVia2.getSelectedItem());
            vias =  ViaController.obtenerViasxIdxDistrito(idTipoVia, idDistrito);
            for (int i = 0; i < vias.size(); i++){
                cmbVia2.addItem(vias.get(i).getNombre());
            }

        }
    }//GEN-LAST:event_cmbDistritoActionPerformed

    private void txtIdentificadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdentificadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdentificadorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar_usuario_button;
    private javax.swing.JButton buscar_usuario_button1;
    private javax.swing.JComboBox cmbDistrito;
    private javax.swing.JComboBox cmbEstado;
    private javax.swing.JComboBox cmbTipoVia1;
    private javax.swing.JComboBox cmbTipoVia2;
    private javax.swing.JComboBox cmbVia1;
    private javax.swing.JComboBox cmbVia2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaSemaforo;
    private javax.swing.JTextField txtCoincidencia;
    private javax.swing.JTextField txtIdentificador;
    // End of variables declaration//GEN-END:variables
}
