/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pe.edu.pucp.linelight.view;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pe.edu.pucp.linelight.controller.DistritoController;
import pe.edu.pucp.linelight.controller.TipoViaController;
import pe.edu.pucp.linelight.controller.ViaController;
import pe.edu.pucp.linelight.controller.semaforoController;
import pe.edu.pucp.linelight.model.Distrito;
import pe.edu.pucp.linelight.model.Semaforo;
import pe.edu.pucp.linelight.model.Tipovia;
import pe.edu.pucp.linelight.model.Via;
import pe.edu.pucp.linelight.util.ValidationUtil;

/**
 *
 * @author USER
 */
public class BuscarVias extends javax.swing.JPanel {

    /**
     * Creates new form BuscarVias
     */
    public BuscarVias() {
        initComponents();
        DefaultTableModel tbm= new DefaultTableModel();
        
        ArrayList<Via> listVias=new ArrayList<Via>();
        ArrayList<Distrito> listDist=new ArrayList<Distrito>();
        cmbVia.removeAllItems();
        cmbVia.addItem("Seleccione");
    //Combo Distrito
        cmbDistrito.removeAllItems();
        cmbDistrito.addItem("Seleccione");
        listDist=DistritoController.obtenerDistritos();
       for (int i=0; i<listDist.size();i++){
            cmbDistrito.addItem(listDist.get(i).getNombre());          
       } 
    //Combo Tipo de via
       cmbTipo.removeAllItems();
       cmbTipo.addItem("Seleccione");
       ArrayList<Tipovia> listTipos=new ArrayList<Tipovia>();
       listTipos=TipoViaController.obtenerTipos();
        for (int i=0; i<listTipos.size();i++){
            cmbTipo.addItem(listTipos.get(i).getDescripcion());          
       } 
       
        listVias=ViaController.obtenerVias();
        cmbVia.removeAllItems();;
        cmbVia.addItem("Seleccione");
        for (int i=0;i<listVias.size();i++){
        cmbVia.addItem(listVias.get(i).getNombre());
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIdentificador = new javax.swing.JTextField();
        cmbDistrito = new javax.swing.JComboBox();
        cmbTipo = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        buscar_usuario_button = new javax.swing.JButton();
        cmbVia = new javax.swing.JComboBox();
        jTextField3 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVia = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 647));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Criterios de Búsqueda"));

        jLabel1.setText("Identificador:");

        jLabel2.setText("Distrito:");

        jLabel3.setText("Tipo Vía:");

        txtIdentificador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdentificadorKeyTyped(evt);
            }
        });

        cmbDistrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDistritoActionPerformed(evt);
            }
        });

        cmbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoActionPerformed(evt);
            }
        });

        jLabel5.setText("Vía:");

        buscar_usuario_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buscar_opt.png"))); // NOI18N
        buscar_usuario_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_usuario_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(396, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbDistrito, 0, 147, Short.MAX_VALUE)
                            .addComponent(cmbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(17, 17, 17)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbVia, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buscar_usuario_button)
                        .addGap(32, 32, 32))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buscar_usuario_button)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cmbDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmbVia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Resultados"));

        tablaVia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificador", "Distrito", "Tipo Via", "Nombre", "Veloc. Maxima", "Descripcion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaVia);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/agregar_opt.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editar_opt.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buscar_usuario_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_usuario_buttonActionPerformed

        DefaultTableModel tbm= new DefaultTableModel();
        String identificador = txtIdentificador.getText();
            if (identificador.isEmpty()) identificador = null;  
        String distrito = (String)cmbDistrito.getSelectedItem();
            if (distrito.equals("Seleccione")) distrito = null;  
        String tipoVia = (String)cmbTipo.getSelectedItem();
            if (tipoVia.equals("Seleccione") ) tipoVia = null;
        String via = (String)cmbVia.getSelectedItem();
            if (via.equals("Seleccione") ) via = null;
        System.out.println("inicio");
        ArrayList<Via> viaCriteria = ViaController.obtenerViaCriteria(identificador,distrito,tipoVia, via);
        System.out.println("fin");
        String [] titulos={"Identificador","Distrito","Tipo de Via","Nombre","Veloc.Máxima","Descripción"};
        tbm.setColumnIdentifiers(titulos);
        tablaVia.setModel(tbm);
        
        for (int i=0;i<viaCriteria.size();i++){
        String datos[]=new String[6];
        String tipo;
        int veloc;
        if(viaCriteria.get(i).getTipovia() != null)
            tipo=TipoViaController.obtenernombTipo(viaCriteria.get(i).getTipovia().getIdTipoVia());
        else
            tipo = "Via no clasificada";
        veloc=(viaCriteria.get(i).getVelocidad());
        //distrito=DistritoController.obtenerNombDistrito(((Via)(viaCriteria.get(i))).getDistrito().getIdDistrito());
        distrito=viaCriteria.get(i).getDistrito().getNombre();
        datos[0]=Long.toString(viaCriteria.get(i).getId().getIdVia());
        datos[1]=distrito;
        datos[2]=tipo;
        datos[3]=viaCriteria.get(i).getNombre();
        datos[4]=Integer.toString(veloc);
        datos[5]=viaCriteria.get(i).getDescripcion();;
        tbm.addRow(datos);
        }
        tablaVia.setModel(tbm);
    }//GEN-LAST:event_buscar_usuario_buttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        NuevaVia nuevo= new NuevaVia();
        nuevo.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Este id sera el id de la vía con el cual obtendre todos
        //los datos necesarios para completar el formulario de editar;
        int numFila =tablaVia.getSelectedRow();
        //System.out.println(numFila);
        if (numFila>=0){
        String dist=(String) tablaVia.getValueAt(numFila,1);
        String tipoVia=(String) tablaVia.getValueAt(numFila,2);
        String nombVia=(String) tablaVia.getValueAt(numFila,3);
        String veloc= (String) tablaVia.getValueAt(numFila, 4);
        String desc=(String) tablaVia.getValueAt(numFila,5);
        String idVia=(String)tablaVia.getValueAt(numFila, 0);
        EditarVia editar=new EditarVia(idVia,dist,tipoVia,nombVia,veloc,desc);
        editar.setVisible(true);
        }
        else{
            int seleccion = JOptionPane.showOptionDialog(
                    BuscarVias.this, // Componente padre
                    "Debe seleccionar una fila", //Mensaje
                    "Mensaje de sugerencia", // Título
                    JOptionPane.WARNING_MESSAGE,
                    JOptionPane.WARNING_MESSAGE,
                    null,    // null para icono por defecto.
                    new Object[] { "Aceptar"},    // null para YES, NO y CANCEL
                    "Aceptar");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmbDistritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDistritoActionPerformed
     //Limpiamos los elemento del combo via 
     cmbVia.removeAllItems();
     int idDistSel;
     
    
      String nombDistrito= (String)cmbDistrito.getSelectedItem();
      String tip=(String)cmbTipo.getSelectedItem();
      if (nombDistrito.equals("Seleccione")){
            cmbVia.addItem("Seleccione");

      //si no he seleccionado nada.
      }else{ // si el usuario ha seleccionado un distrito
          //cmbVia1.removeAll();
          String tipo=(String)cmbTipo.getSelectedItem();
          idDistSel=DistritoController.obteneridDistrito(nombDistrito);
           ArrayList<Via> listVias=new ArrayList<Via>();
          if (tipo.equals("Seleccione")){
          listVias=ViaController.obtenerVias(idDistSel);
          cmbVia.addItem("Seleccione");
          for (int i=0;i<listVias.size();i++){             
          cmbVia.addItem(listVias.get(i).getNombre());
          }
          }
          else{
              
              int idTipo=TipoViaController.obteneridTipo(tipo);
              listVias=ViaController.obtenerViasxIdxDistrito(idTipo, idDistSel);
              cmbVia.addItem("Seleccione");
              for (int i=0;i<listVias.size();i++){             
              cmbVia.addItem(listVias.get(i).getNombre());
                }
              
                  }    
      }
    }//GEN-LAST:event_cmbDistritoActionPerformed

    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed
        cmbVia.removeAllItems();
        String tipo=(String)cmbTipo.getSelectedItem();
        ArrayList<Via> listVias=new ArrayList<Via>();
        if (tipo.equals("Seleccione")){
        cmbVia.addItem("Seleccione");
        listVias=ViaController.obtenerVias();
        for (int i=0;i<listVias.size();i++){             
            cmbVia.addItem(listVias.get(i).getNombre());
          } }
        else{
        int idTipo=TipoViaController.obteneridTipo(tipo);
        String nombDistrito= (String)cmbDistrito.getSelectedItem();
        if (nombDistrito.equals("Seleccione")){
            listVias=ViaController.obtenerViasxId(idTipo);
        }
        else{
            int idDistSel=DistritoController.obteneridDistrito(nombDistrito);
            listVias=ViaController.obtenerViasxIdxDistrito(idTipo, idDistSel);
            
        }
        cmbVia.addItem("Seleccione");
        for (int i=0;i<listVias.size();i++){             
            cmbVia.addItem(listVias.get(i).getNombre());
          } 
        
        }
        
    }//GEN-LAST:event_cmbTipoActionPerformed

    private void txtIdentificadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentificadorKeyTyped
        // TODO add your handling code here:
        ValidationUtil.validateNumTam(txtIdentificador.getText(), 20, evt);
    }//GEN-LAST:event_txtIdentificadorKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar_usuario_button;
    private javax.swing.JComboBox cmbDistrito;
    private javax.swing.JComboBox cmbTipo;
    private javax.swing.JComboBox cmbVia;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTable tablaVia;
    private javax.swing.JTextField txtIdentificador;
    // End of variables declaration//GEN-END:variables
}
