/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pe.edu.pucp.linelight.view;

import javax.swing.JOptionPane;
import pe.edu.pucp.linelight.controller.ConfiguracionSistemaController;
import pe.edu.pucp.linelight.model.Configuracionsistema;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import pe.edu.pucp.linelight.util.ValidationUtil;

/**
 *
 * @author Charito
 */
public class PanelConfiguracion extends javax.swing.JPanel {

    /**
     * Creates new form ConfiguracionPanel
     */
    public PanelConfiguracion() {
        initComponents();
        this.setBackground(new java.awt.Color(240, 240, 240));
        
        Configuracionsistema configuracionSistema = ConfiguracionSistemaController.getConfiguracionSistemaById(1);
        this.jTextField1.setText("" + configuracionSistema.getTVerdeMax());
        this.jTextField2.setText("" + configuracionSistema.getTVerdeMin());
        this.jTextField3.setText("" + configuracionSistema.getTRojoMax());
        this.jTextField4.setText("" + configuracionSistema.getTRojoMin());
        this.jTextField8.setText("" + configuracionSistema.getTDefault());
        this.jTextField9.setText("" + configuracionSistema.getNPeriodo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(800, 647));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Semáforos"));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(720, 226));

        jLabel1.setText("Tiempo máximo en verde:");

        jLabel2.setText("Tiempo mínimo en verde:");

        jLabel3.setText("Tiempo mínimo en rojo:");

        jLabel4.setText("Tiempo máximo en rojo:");

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editar_opt.png"))); // NOI18N
        jButton1.setText("Registar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel10.setText("Tiempo por defecto:");

        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField8KeyTyped(evt);
            }
        });

        jLabel11.setText("Tiempo de periódo:");

        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField9KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField8)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(342, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("");
        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//            WindowConfigSemaforos verde= new WindowConfigSemaforos();
//            verde.setVisible(true);
        
        // TODO add your handling code here:
        int seleccion = JOptionPane.showOptionDialog(
                PanelConfiguracion.this, // Componente padre
                "¿Esta seguro que desea guardar los Parámetros?", //Mensaje
                "Mensaje de confirmación", // Título
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,    // null para icono por defecto.
                new Object[] { "Si", "No"},    // null para YES, NO y CANCEL
                "Si");
        
        if (seleccion != -1)
        {
            if(seleccion == 0)
               {
                   try{
                   /*Se necesita nombre de simulacion, tiempo de ejecucion*/
                   Configuracionsistema editar_configuracionSistema = ConfiguracionSistemaController.getConfiguracionSistemaById(1);
                   
//                 ejecucionAlgoritmo.setId(new EjecucionalgoritmoId(1,1,user.getIdUsuario(),1));                   
                   editar_configuracionSistema.setTVerdeMax(Integer.parseInt(this.jTextField1.getText()));
                   editar_configuracionSistema.setTVerdeMin(Integer.parseInt(this.jTextField2.getText()));
                   editar_configuracionSistema.setTRojoMax(Integer.parseInt(this.jTextField3.getText()));                   
                   editar_configuracionSistema.setTRojoMin(Integer.parseInt(this.jTextField4.getText()));                                      
                   editar_configuracionSistema.setTDefault(Integer.parseInt(this.jTextField8.getText()));                   
                   editar_configuracionSistema.setTPeriodo(1);
                   editar_configuracionSistema.setNPeriodo(120);
                   editar_configuracionSistema.setTCiclo(120);
                   editar_configuracionSistema.setConversionKmM(0.277777);                           
                   
                   ConfiguracionSistemaController.editarConfiguracionSistema(editar_configuracionSistema);
                   JOptionPane.showMessageDialog(PanelConfiguracion.this, "Variables Actualizada","Acción",INFORMATION_MESSAGE,null);
                   }
                   catch(Exception e){
                       e.printStackTrace();
                       JOptionPane.showMessageDialog(PanelConfiguracion.this, "Imposible Actualizar Variables","Acción",ERROR_MESSAGE,null);
                   }
                   
                   
                   
                                      
                   /*CODIGO PARA AGREGAR UN Configuracionsistema Y LLAMA AL CONTROLLER**/
//                   /*Se necesita nombre de simulacion, tiempo de ejecucion*/
//                   Configuracionsistema configuracionSistema = new Configuracionsistema();                   
//                   
//                  //El id de la ejecucion                  
//                  int id = ConfiguracionSistemaController.getNextId();
//                  
//                  //Registramos la ejecucion
//                  configuracionSistema.setIdConfiguracionSistema(id);
//                   
////                   ejecucionAlgoritmo.setId(new EjecucionalgoritmoId(1,1,user.getIdUsuario(),1));                   
//                   configuracionSistema.setTVerdeMax(Integer.parseInt(this.jTextField1.getText()));
//                   configuracionSistema.setTVerdeMin(Integer.parseInt(this.jTextField2.getText()));
//                   configuracionSistema.setTRojoMax(Integer.parseInt(this.jTextField3.getText()));                   
//                   configuracionSistema.setTRojoMin(Integer.parseInt(this.jTextField4.getText()));                                      
//                   configuracionSistema.setTDefault(Integer.parseInt(this.jTextField8.getText()));                   
//                   configuracionSistema.setTPeriodo(1);
//                   configuracionSistema.setNPeriodo(120);
//                   configuracionSistema.setTCiclo(120);
//                   configuracionSistema.setConversionKmM(0.277777);                           
//                   
//                   int ok =ConfiguracionSistemaController.agregarConfiguracionSistema(configuracionSistema);
//                   if(ok == 1)                   
//                   {
//                       JOptionPane.showMessageDialog(PanelConfiguracion.this, "Item agregado","Acción",INFORMATION_MESSAGE,null);
//                       //PanelSimulacionMonitoreo.this.dispose();
//                   }
//                   else
//                   {
//                       JOptionPane.showMessageDialog(PanelConfiguracion.this, "Imposible agregar item","Acción",ERROR_MESSAGE,null);
//                   }

               }
        }            
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
        ValidationUtil.validateNumTam(jTextField1.getText(), 2, evt);
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        // TODO add your handling code here:
        ValidationUtil.validateNumTam(jTextField2.getText(), 2, evt);
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jTextField8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyTyped
        // TODO add your handling code here:
        ValidationUtil.validateNumTam(jTextField8.getText(), 2, evt);
    }//GEN-LAST:event_jTextField8KeyTyped

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        // TODO add your handling code here:
        ValidationUtil.validateNumTam(jTextField3.getText(), 2, evt);
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        // TODO add your handling code here:
        ValidationUtil.validateNumTam(jTextField4.getText(), 2, evt);
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jTextField9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyTyped
        // TODO add your handling code here:
        ValidationUtil.validateNumTam(jTextField9.getText(), 3, evt);
    }//GEN-LAST:event_jTextField9KeyTyped
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
