/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pe.edu.pucp.linelight.view;

import java.net.URL;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRExporter;
import net.sf.jasperreports.engine.JRExporterParameter;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.export.JRPdfExporter;
import net.sf.jasperreports.view.JasperViewer;
import pe.edu.pucp.linelight.controller.UsuarioController;
import pe.edu.pucp.linelight.reportClasses.UsuariosReport;

/**
 *
 * @author Charito
 */
public class SeguridadReportes extends javax.swing.JPanel {

    /**
     * Creates new form SeguridadReportes
     */
    public SeguridadReportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 647));

        jButton1.setText("Reporte");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jButton1)
                .addContainerGap(195, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jButton1)
                .addContainerGap(150, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    JasperPrint jp;
    
public void init_usuarios() throws JRException, ParseException{
        URL in = null;
      try{
          in = this.getClass().getResource("/pe/edu/pucp/linelight/reports/usuariosReport.jasper");
          List<UsuariosReport> lista = new ArrayList<>();
          UsuariosReport raut=new UsuariosReport();
          raut.setUsuarios(UsuarioController.getAllUsuarios());
        
         
         lista.add(raut);
          JRBeanCollectionDataSource beanCollectionDataSource=new JRBeanCollectionDataSource(lista);
          jp=JasperFillManager.fillReport(in.getPath(), new HashMap(),beanCollectionDataSource);    
        } catch(JRException e){
           e.printStackTrace();
      }
  }


    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            //        try {
            init_usuarios();
        } catch (JRException ex) {
            Logger.getLogger(SeguridadReportes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(SeguridadReportes.class.getName()).log(Level.SEVERE, null, ex);
        }
//        } catch (JRException ex) {
//            Logger.getLogger(SeguridadReportes.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (ParseException ex) {
//            Logger.getLogger(SeguridadReportes.class.getName()).log(Level.SEVERE, null, ex);
//        }
//            JRExporter exporter = new JRPdfExporter();
//        
//        exporter.setParameter(JRExporterParameter.JASPER_PRINT, jp);
//        exporter.setParameter(JRExporterParameter.OUTPUT_FILE, new java.io.File("reportePDF.pdf"));
//        try {
//            exporter.exportReport();
//        } catch (JRException ex) {
//            Logger.getLogger(SeguridadReportes.class.getName()).log(Level.SEVERE, null, ex);
//        }
           JasperViewer jviewer= new JasperViewer(jp,false);
           jviewer.setTitle("Reporte");
           jviewer.setVisible(true);
       
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
