/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pe.edu.pucp.linelight.view;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pe.edu.pucp.linelight.controller.DistritoController;
import pe.edu.pucp.linelight.controller.TipoViaController;
import pe.edu.pucp.linelight.controller.ViaController;
import pe.edu.pucp.linelight.model.Distrito;
import pe.edu.pucp.linelight.model.Tramo;
import pe.edu.pucp.linelight.model.Zona;

/**
 *
 * @author USER
 */
public class TramosxVias extends javax.swing.JFrame {

    /**
     * Creates new form TramosxVias
     */
    public TramosxVias() {
        initComponents();
    }
     public TramosxVias(long idvia,String distrito,String via, String tipo) {
        initComponents();
        DefaultTableModel tbm= new DefaultTableModel();
        ArrayList<Tramo> listaTramos=new ArrayList<Tramo>();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        txtDistrito.setText(distrito);
        txtVia.setText(via);
        txtTipo.setText(tipo);
        //System.out.println(idvia);
        
        int idDistrito=DistritoController.obteneridDistrito(distrito);
        //necesito el mapa del distrito cargado
        /*
        Distrito dist=DistritoController.obtenerDistrito(distrito);
         Zona zona0 = (Zona) dist.getZonas().toArray()[0];
        Image img = Toolkit.getDefaultToolkit().createImage(zona0.getImagen());
        ImageIcon icon =new ImageIcon(img);
        labelmapa.setIcon(icon);
*/
        
        //System.out.println(listaTramos.size());
        
        listaTramos=ViaController.obtenerTramosxVias(idvia, idDistrito);
        String [] titulos={"Estado","Tramo"};
        tbm.setColumnIdentifiers(titulos);
        tablaTramos.setModel(tbm);       
        for (int i=0;i<listaTramos.size();i++){
        String datos[]=new String[2];
        boolean estado=listaTramos.get(i).getEstado();
        if (estado==true) datos[0]="Habilitado";
        else{datos[0]="Deshabilitado";}
        int tramo=listaTramos.get(i).getId().getIdTramo();
        datos[1]= "Tramo"+" "+ tramo;
        tbm.addRow(datos);
        }
        tablaTramos.setModel(tbm);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDistrito = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtVia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTramos = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        labelmapa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Habilitar/Deshabilitar Tramo");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Informacion de la via"));

        jLabel1.setText("Distrito:");

        txtDistrito.setEditable(false);

        jLabel2.setText("Vía:");

        txtVia.setEditable(false);

        jLabel3.setText("Tipo Vía:");

        txtTipo.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                    .addComponent(txtVia))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtVia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Habilitar/Deshabilitar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tablaTramos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaTramos);

        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelmapa, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(labelmapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int [] numFila = tablaTramos.getSelectedRows();
                        if (numFila.length != 0){
                        String nombre = txtVia.getText();
                        String distrito = txtDistrito.getText();
                        int idDist = DistritoController.obteneridDistrito(distrito);
                        String tipoVia = txtTipo.getText();
                        int idTipo = TipoViaController.obteneridTipo(tipoVia);
                        long idVia = ViaController.obtenerIdVia(nombre, idTipo, idDist);
                                
          int seleccion = JOptionPane.showOptionDialog(
                    TramosxVias.this, // Componente padre
                    "¿Esta seguro que desea guardar los cambios?", //Mensaje
                    "Mensaje de confirmación", // Título
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,    // null para icono por defecto.
                    new Object[] { "Si", "No"},    // null para YES, NO y CANCEL
                    "Si");
        //Dependiendo de la seleccion
        if (seleccion != -1)//si ha seleccionado alguna opcion
                {
                   if(seleccion == 1)//si ha seleccionado no
                   {
                   }
                   else 
                   {
                       for (int i = 0; i < numFila.length; i++){
                                        String tramo =(String)tablaTramos.getValueAt(numFila[i], 1);
                                        int idTramo = Integer.parseInt(tramo.substring(6, tramo.length()));
                                        String e =(String)tablaTramos.getValueAt(numFila[i], 0);
                                        //System.out.println(idVia);
                                        Boolean estado=true;
                                        if (e.equals("Habilitado")) estado=false;
                                        if (e.equals("Deshabilitado")) estado=true;
                                         ViaController.cambiarEstadoTramo(estado,idVia,idDist,idTramo);
                                        
                       }
                       DefaultTableModel tbm1 = new DefaultTableModel();
                       ArrayList<Tramo> listaTramos=new ArrayList<Tramo>();
                       listaTramos=ViaController.obtenerTramosxVias(idVia, idDist);
                       String [] titulos = {"Estado","Tramo"};
                       tbm1.setColumnIdentifiers(titulos);
                       tablaTramos.setModel(tbm1);    
                       for (int i=0; i < listaTramos.size(); i++){
                        String datos[] = new String[2];
                        boolean est=listaTramos.get(i).getEstado();
                        if (est==true) datos[0]="Habilitado";
                        else{datos[0]="Deshabilitado";}
                        int tram=listaTramos.get(i).getId().getIdTramo();
                        datos[1]= "Tramo"+" "+Integer.toString(tram);
                        tbm1.addRow(datos);
                        }
                       
                            tablaTramos.setModel(tbm1);
                            tablaTramos.repaint();
                      
                       //this.dispose();

                   }
                }
        }else{
        int seleccion = JOptionPane.showOptionDialog(
                    TramosxVias.this, // Componente padre
                    "Selecciona alguna fila", //Mensaje
                    "Mensaje de sugerencia", // Título
                    JOptionPane.OK_OPTION,
                    JOptionPane.OK_OPTION,
                    null,    // null para icono por defecto.
                    new Object[] { "Aceptar"},    // null para YES, NO y CANCEL
                    "Si");
        if (seleccion!=-1){
        }
         
        }
       
       
       
       // this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TramosxVias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TramosxVias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TramosxVias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TramosxVias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TramosxVias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelmapa;
    private javax.swing.JTable tablaTramos;
    private javax.swing.JTextField txtDistrito;
    private javax.swing.JTextField txtTipo;
    private javax.swing.JTextField txtVia;
    // End of variables declaration//GEN-END:variables
}
