/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pe.edu.pucp.linelight.view;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author PC-HP
 */
public class WindowMaintInit extends javax.swing.JFrame {

    /**
     * Creates new form WindowMaintInit
     */
    public WindowMaintInit() {
//        setUndecorated(true);
        setTitle("LineLight - Menú Principal");
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        initComponents();
        
//        Dimension d=super.getToolkit().getScreenSize();
//        System.out.println(d.getHeight()+"-"+d.getWidth());
//        super.setSize(d);
        super.setVisible(true);
//        this.panelMonitoreo.setVisible(false);
//        this.panelSimulacion.setVisible(false);
//        this.panelReportes.setVisible(false);
//        this.panelMonitoreo.setBackground(Color.decode("#E8ECED"));
//        this.panelSimulacion.setBackground(Color.decode("#E8ECED"));
//        this.panelReportes.setBackground(Color.decode("#E8ECED"));
        this.getContentPane().setBackground(Color.decode("#E8ECED"));
        ImageIcon img=new ImageIcon("mapa.png");
        JLabel label=new JLabel();
        label.setIcon(img);
//        this.panelMapa.add(label);
//        this.panelSubMenuReportes.setVisible(false);
//        this.getContentPane().setBackground(Color.decode("#C3DBDB"));
//        panelMonitoreo.setBackground(Color.decode("#C3DBDB"));
//        panelSimulacion.setBackground(Color.decode("#C3DBDB"));
//        panelSubMenuReportes.setBackground(Color.decode("#C3DBDB"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void ArrastrarVentana(Component elemento)/* elemento: Debe ser la instancia del JFrame*/
    {
        elemento.addMouseMotionListener(new java.awt.event.MouseMotionListener()
        {

            @Override
            public void mouseDragged(MouseEvent e) {
                int x2 = e.getXOnScreen();
                int y2 = e.getYOnScreen();
                setLocation(x2,y2);
            }

            @Override
            public void mouseMoved(MouseEvent e) {
                
            }
            
//            @Override
//            public void mousePressed(MouseEvent e)
//            {
//            setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
//            int posX = getX();
//            int posY = getY();
//            int x1 = e.getXOnScreen();
//            int y1 = e.getYOnScreen();
//            }
          
        });
    };
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenedor = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        btnMonitoreo = new javax.swing.JButton();
        btnSimulacion = new javax.swing.JButton();
        btnConfiguracion = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLogin3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(0, 102, 102));
        setBounds(new java.awt.Rectangle(0, 22, 500, 500));
        setMinimumSize(new java.awt.Dimension(500, 650));

        panelContenedor.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 102), null));
        panelContenedor.setForeground(new java.awt.Color(0, 51, 51));
        panelContenedor.setPreferredSize(new java.awt.Dimension(400, 526));

        btnMonitoreo.setBackground(new java.awt.Color(222, 227, 227));
        btnMonitoreo.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        btnMonitoreo.setForeground(new java.awt.Color(0, 51, 51));
        btnMonitoreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/monitoreo.png"))); // NOI18N
        btnMonitoreo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMonitoreo.setLabel("<html>Monitoreo<br>en línea</html>");
        btnMonitoreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonitoreoActionPerformed(evt);
            }
        });

        btnSimulacion.setBackground(new java.awt.Color(222, 227, 227));
        btnSimulacion.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        btnSimulacion.setForeground(new java.awt.Color(0, 51, 51));
        btnSimulacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/simulacion.png"))); // NOI18N
        btnSimulacion.setLabel("<html>Simulación<br>Histórica</html>");
        btnSimulacion.setPreferredSize(new java.awt.Dimension(165, 65));
        btnSimulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimulacionActionPerformed(evt);
            }
        });

        btnConfiguracion.setBackground(new java.awt.Color(222, 227, 227));
        btnConfiguracion.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        btnConfiguracion.setForeground(new java.awt.Color(0, 51, 51));
        btnConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/configuracion.png"))); // NOI18N
        btnConfiguracion.setLabel("<html>Adm. de<br>Sistema</html>");
        btnConfiguracion.setMaximumSize(new java.awt.Dimension(165, 65));
        btnConfiguracion.setMinimumSize(new java.awt.Dimension(165, 65));
        btnConfiguracion.setPreferredSize(new java.awt.Dimension(165, 65));

        btnReportes.setBackground(new java.awt.Color(222, 227, 227));
        btnReportes.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(0, 51, 51));
        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reportes.png"))); // NOI18N
        btnReportes.setText("Reportes");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        jLabel2.setText("Bienvenido, Usuario.");

        jLabel3.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        jLabel3.setText("Martes 08/04/2014 20:00");

        btnLogin3.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        btnLogin3.setText("Cerrar Sesión");
        btnLogin3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContenedorLayout.createSequentialGroup()
                .addGap(696, 696, 696)
                .addComponent(jSeparator1))
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContenedorLayout.createSequentialGroup()
                        .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(panelContenedorLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56)
                                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMonitoreo, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelContenedorLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogin3)
                        .addGap(131, 131, 131))))
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnLogin3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContenedorLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelContenedorLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMonitoreo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
       WindowReportes wr=new WindowReportes();
       wr.setVisible(true);
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnSimulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimulacionActionPerformed
          WindowSimulacion ws=new WindowSimulacion();
          ws.setVisible(true);
          this.setVisible(false);
//        this.panelMonitoreo.setVisible(false);
    }//GEN-LAST:event_btnSimulacionActionPerformed

    private void btnMonitoreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonitoreoActionPerformed
        WindowMonitoreo wr=new WindowMonitoreo();
        wr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMonitoreoActionPerformed

    private void btnLogin3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin3ActionPerformed

        WindowMaintInit wm=new WindowMaintInit();
        this.setVisible(false);
    }//GEN-LAST:event_btnLogin3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowMaintInit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowMaintInit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowMaintInit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowMaintInit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WindowMaintInit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfiguracion;
    private javax.swing.JButton btnLogin3;
    private javax.swing.JButton btnMonitoreo;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnSimulacion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelContenedor;
    // End of variables declaration//GEN-END:variables
}
