/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pe.edu.pucp.linelight.view;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import org.jdesktop.xswingx.PromptSupport;
import pe.edu.pucp.linelight.controller.UsuarioController;
import pe.edu.pucp.linelight.model.Usuario;
import pe.edu.pucp.linelight.util.GeneralUtil;
import pe.edu.pucp.linelight.util.ValidationUtil;
import pe.edu.pucp.linelight.util.MailUtil;

/**
 *
 * @author Julio
 */
public class WindowCambiarContrasena extends javax.swing.JFrame {

    /**
     * Creates new form WindowOlvidasteContrasena
     */
    public WindowCambiarContrasena() {
        initComponents();
        Image icon = new ImageIcon(getClass().getResource("/images/semaforo.png")).getImage();
        setIconImage(icon);        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        PromptSupport.setPrompt("Contraseña Antigua", this.jPassword_ant);
         PromptSupport.setPrompt("Contraseña Nueva", this.jPassword_new);
          PromptSupport.setPrompt("Confirmar Contraseña Nueva", this.jPassword_new2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sendPasswordButton = new javax.swing.JButton();
        sendPasswordButton1 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPassword_ant = new javax.swing.JPasswordField();
        jPassword_new = new javax.swing.JPasswordField();
        jPassword_new2 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        sendPasswordButton.setText("Aceptar");
        sendPasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendPasswordButtonActionPerformed(evt);
            }
        });

        sendPasswordButton1.setText("Cancelar");
        sendPasswordButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendPasswordButton1ActionPerformed(evt);
            }
        });

        jLabel27.setForeground(new java.awt.Color(255, 0, 0));
        jLabel27.setText("(*)");

        jLabel28.setForeground(new java.awt.Color(255, 0, 0));
        jLabel28.setText("(*)");

        jLabel29.setForeground(new java.awt.Color(255, 0, 0));
        jLabel29.setText("(*)");

        jPassword_ant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPassword_antActionPerformed(evt);
            }
        });
        jPassword_ant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPassword_antKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPassword_antKeyTyped(evt);
            }
        });

        jPassword_new.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPassword_newKeyTyped(evt);
            }
        });

        jPassword_new2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPassword_new2ActionPerformed(evt);
            }
        });
        jPassword_new2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPassword_new2KeyTyped(evt);
            }
        });

        jLabel1.setText("Antigua Contraseña:");

        jLabel2.setText("Nueva Contraseña:");

        jLabel3.setText("Confirmación:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(sendPasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sendPasswordButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPassword_ant, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(jPassword_new, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPassword_new2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel28)
                        .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel27))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPassword_ant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPassword_new, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jPassword_new2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel29)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendPasswordButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendPasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendPasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendPasswordButtonActionPerformed
           if(GeneralUtil.getUsuario_sesion().getPassword().equals(this.jPassword_ant.getText())){
               if(this.jPassword_new.getText().equals(this.jPassword_new2.getText())){
                   GeneralUtil.getUsuario_sesion().setPassword(this.jPassword_new.getText());
                   try{
                   UsuarioController.editarUsuario(GeneralUtil.getUsuario_sesion());
                   JOptionPane.showMessageDialog(WindowCambiarContrasena.this, "Contraseña Cambiada","Acción",INFORMATION_MESSAGE,null);
                   this.dispose();
                    }catch(Exception e){
                        e.printStackTrace();
                         JOptionPane.showMessageDialog(WindowCambiarContrasena.this, "No se pudo cambiar la contraseña","Error",ERROR_MESSAGE,null);
                    }
               }else{
               
               JOptionPane.showMessageDialog(WindowCambiarContrasena.this, "Error al validar la nueva contraseña","Error",ERROR_MESSAGE,null);
                  
               }
           
           
           }else{
               JOptionPane.showMessageDialog(WindowCambiarContrasena.this, "Antigua Contraseña inválida","Error",ERROR_MESSAGE,null);
                  
           }
 
    }//GEN-LAST:event_sendPasswordButtonActionPerformed

    private void sendPasswordButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendPasswordButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendPasswordButton1ActionPerformed

    private void jPassword_antKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPassword_antKeyPressed
         //ValidationUtil.validateLenght2(this.jPassword_ant.getText(),20, evt);
    }//GEN-LAST:event_jPassword_antKeyPressed

    private void jPassword_newKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPassword_newKeyTyped
         ValidationUtil.validateLenght4(this.jPassword_new.getText(),20, evt);
    }//GEN-LAST:event_jPassword_newKeyTyped

    private void jPassword_new2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPassword_new2KeyTyped
         ValidationUtil.validateLenght4(this.jPassword_new2.getText(),20, evt);
    }//GEN-LAST:event_jPassword_new2KeyTyped

    private void jPassword_new2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPassword_new2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPassword_new2ActionPerformed

    private void jPassword_antActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPassword_antActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPassword_antActionPerformed

    private void jPassword_antKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPassword_antKeyTyped
        ValidationUtil.validateLenght4(this.jPassword_new2.getText(),20, evt);
    }//GEN-LAST:event_jPassword_antKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowCambiarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowCambiarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowCambiarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowCambiarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WindowCambiarContrasena().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPassword_ant;
    private javax.swing.JPasswordField jPassword_new;
    private javax.swing.JPasswordField jPassword_new2;
    private javax.swing.JButton sendPasswordButton;
    private javax.swing.JButton sendPasswordButton1;
    // End of variables declaration//GEN-END:variables
}
