/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pe.edu.pucp.linelight.view;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author PC-HP
 */
public class WindowConfiguracionSistema extends javax.swing.JFrame {

    /**
     * Creates new form WindowMaintInit
     */
    public WindowConfiguracionSistema() {
        setUndecorated(true);
        initComponents();
        ArrastrarVentana(this);
//        Dimension d=super.getToolkit().getScreenSize();
//        System.out.println(d.getHeight()+"-"+d.getWidth());
//        super.setSize(d);
        super.setVisible(true);
        this.panelMonitoreo.setVisible(false);
//        this.panelSimulacion.setVisible(false);
//        this.panelReportes.setVisible(false);
        this.panelMonitoreo.setBackground(Color.decode("#E8ECED"));
//        this.panelSimulacion.setBackground(Color.decode("#E8ECED"));
//        this.panelReportes.setBackground(Color.decode("#E8ECED"));
        this.getContentPane().setBackground(Color.decode("#E8ECED"));
        ImageIcon img=new ImageIcon("mapa.png");
        JLabel label=new JLabel();
        label.setIcon(img);
//        this.panelMapa.add(label);
//        this.panelSubMenuReportes.setVisible(false);
//        this.getContentPane().setBackground(Color.decode("#C3DBDB"));
//        panelMonitoreo.setBackground(Color.decode("#C3DBDB"));
//        panelSimulacion.setBackground(Color.decode("#C3DBDB"));
//        panelSubMenuReportes.setBackground(Color.decode("#C3DBDB"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void ArrastrarVentana(Component elemento)/* elemento: Debe ser la instancia del JFrame*/
    {
        elemento.addMouseMotionListener(new java.awt.event.MouseMotionListener()
        {

            @Override
            public void mouseDragged(MouseEvent e) {
                int x2 = e.getXOnScreen();
                int y2 = e.getYOnScreen();
                setLocation(x2,y2);
            }

            @Override
            public void mouseMoved(MouseEvent e) {
                
            }
            
//            @Override
//            public void mousePressed(MouseEvent e)
//            {
//            setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
//            int posX = getX();
//            int posY = getY();
//            int x1 = e.getXOnScreen();
//            int y1 = e.getYOnScreen();
//            }
          
        });
    };
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenedor = new javax.swing.JPanel();
        panelMonitoreo = new javax.swing.JPanel();
        btnReportes = new javax.swing.JButton();
        btnReportes1 = new javax.swing.JButton();
        btnReportes2 = new javax.swing.JButton();
        btnReportes3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        iconoMinimizar = new javax.swing.JLabel();
        iconoMaximizar = new javax.swing.JLabel();
        iconoCerrar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLogin3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        iconoMinimizar1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(0, 102, 102));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(1360, 650));

        panelContenedor.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 102), null));
        panelContenedor.setForeground(new java.awt.Color(0, 51, 51));
        panelContenedor.setPreferredSize(new java.awt.Dimension(1360, 700));

        panelMonitoreo.setPreferredSize(new java.awt.Dimension(727, 300));

        btnReportes.setBackground(new java.awt.Color(222, 227, 227));
        btnReportes.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(0, 51, 51));
        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        btnReportes.setText("<html>Mantenimiento<br>de Usuarios</html>");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        btnReportes1.setBackground(new java.awt.Color(222, 227, 227));
        btnReportes1.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        btnReportes1.setForeground(new java.awt.Color(0, 51, 51));
        btnReportes1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calle.png"))); // NOI18N
        btnReportes1.setText("<html>Mantenimiento de Calles</html>");
        btnReportes1.setToolTipText("");
        btnReportes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportes1ActionPerformed(evt);
            }
        });

        btnReportes2.setBackground(new java.awt.Color(222, 227, 227));
        btnReportes2.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        btnReportes2.setForeground(new java.awt.Color(0, 51, 51));
        btnReportes2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/semaforo.png"))); // NOI18N
        btnReportes2.setText("<html>Mantenimiento de Semáforos</html>");
        btnReportes2.setToolTipText("");
        btnReportes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportes2ActionPerformed(evt);
            }
        });

        btnReportes3.setBackground(new java.awt.Color(222, 227, 227));
        btnReportes3.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        btnReportes3.setForeground(new java.awt.Color(0, 51, 51));
        btnReportes3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/conf_mant.png"))); // NOI18N
        btnReportes3.setText("<html>Parámetros del<br>Algoritmo</html>");
        btnReportes3.setToolTipText("");
        btnReportes3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportes3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMonitoreoLayout = new javax.swing.GroupLayout(panelMonitoreo);
        panelMonitoreo.setLayout(panelMonitoreoLayout);
        panelMonitoreoLayout.setHorizontalGroup(
            panelMonitoreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMonitoreoLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(panelMonitoreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelMonitoreoLayout.createSequentialGroup()
                        .addComponent(btnReportes2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReportes1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMonitoreoLayout.createSequentialGroup()
                        .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(btnReportes3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        panelMonitoreoLayout.setVerticalGroup(
            panelMonitoreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMonitoreoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMonitoreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReportes3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(panelMonitoreoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReportes2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReportes1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(73, 121, 149));

        iconoMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/min.png"))); // NOI18N

        iconoMaximizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/min.png"))); // NOI18N

        iconoCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/min.png"))); // NOI18N
        iconoCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconoCerrarMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(201, 216, 231));
        jLabel1.setText("Configuración del Sistema");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconoMinimizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iconoMaximizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iconoCerrar)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconoMinimizar)
                    .addComponent(iconoMaximizar)
                    .addComponent(iconoCerrar)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        jLabel2.setText("Bienvenido, Usuario.");

        btnLogin3.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        btnLogin3.setText("Cerrar Sesión");
        btnLogin3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        jLabel3.setText("Martes 08/04/2014 20:00");

        iconoMinimizar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContenedorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContenedorLayout.createSequentialGroup()
                        .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelContenedorLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panelMonitoreo, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelContenedorLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE))
                            .addGroup(panelContenedorLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(iconoMinimizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLogin3)))
                        .addGap(15, 15, 15)))
                .addContainerGap())
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContenedorLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLogin3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iconoMinimizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelContenedorLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addGap(16, 16, 16)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelMonitoreo, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogin3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin3ActionPerformed

        WindowMaintInit wm=new WindowMaintInit();
        this.setVisible(false);
    }//GEN-LAST:event_btnLogin3ActionPerformed

    private void iconoCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconoCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_iconoCerrarMouseClicked

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        //        if (this.panelSubMenuReportes.isVisible())
        //            this.panelSubMenuReportes.setVisible(false);
        //        else
        //            this.panelSubMenuReportes.setVisible(true);
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnReportes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportes1ActionPerformed

    private void btnReportes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportes2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportes2ActionPerformed

    private void btnReportes3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportes3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportes3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowMonitoreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowMonitoreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowMonitoreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowMonitoreo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WindowMonitoreo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin3;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnReportes1;
    private javax.swing.JButton btnReportes2;
    private javax.swing.JButton btnReportes3;
    private javax.swing.JLabel iconoCerrar;
    private javax.swing.JLabel iconoMaximizar;
    private javax.swing.JLabel iconoMinimizar;
    private javax.swing.JLabel iconoMinimizar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelContenedor;
    private javax.swing.JPanel panelMonitoreo;
    // End of variables declaration//GEN-END:variables
}
