package pe.edu.pucp.linelight.model;
// Generated 03/06/2014 08:23:06 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ejecucionalgoritmo generated by hbm2java
 */
public class Ejecucionalgoritmo  implements java.io.Serializable {


     private EjecucionalgoritmoId id;
     private Paramalgoritmo paramalgoritmo;
     private Usuario usuario;
     private Configuracionsistema configuracionsistema;
     private Date fecha;
     private Double velocidadMaxima;
     private String nombreEjecucion;
     private Double velocidadHistorica;
     private Set vehiculos = new HashSet(0);
     private Set ejecucionalgoritmoxsemaforos = new HashSet(0);
     private Set ejecucionalgoritmoxcuadraxnodos = new HashSet(0);

    public Ejecucionalgoritmo() {
    }

	
    public Ejecucionalgoritmo(EjecucionalgoritmoId id, Paramalgoritmo paramalgoritmo, Usuario usuario, Configuracionsistema configuracionsistema) {
        this.id = id;
        this.paramalgoritmo = paramalgoritmo;
        this.usuario = usuario;
        this.configuracionsistema = configuracionsistema;
    }
    public Ejecucionalgoritmo(EjecucionalgoritmoId id, Paramalgoritmo paramalgoritmo, Usuario usuario, Configuracionsistema configuracionsistema, Date fecha, Double velocidadMaxima, String nombreEjecucion, Double velocidadHistorica, Set vehiculos, Set ejecucionalgoritmoxsemaforos, Set ejecucionalgoritmoxcuadraxnodos) {
       this.id = id;
       this.paramalgoritmo = paramalgoritmo;
       this.usuario = usuario;
       this.configuracionsistema = configuracionsistema;
       this.fecha = fecha;
       this.velocidadMaxima = velocidadMaxima;
       this.nombreEjecucion = nombreEjecucion;
       this.velocidadHistorica = velocidadHistorica;
       this.vehiculos = vehiculos;
       this.ejecucionalgoritmoxsemaforos = ejecucionalgoritmoxsemaforos;
       this.ejecucionalgoritmoxcuadraxnodos = ejecucionalgoritmoxcuadraxnodos;
    }
   
    public EjecucionalgoritmoId getId() {
        return this.id;
    }
    
    public void setId(EjecucionalgoritmoId id) {
        this.id = id;
    }
    public Paramalgoritmo getParamalgoritmo() {
        return this.paramalgoritmo;
    }
    
    public void setParamalgoritmo(Paramalgoritmo paramalgoritmo) {
        this.paramalgoritmo = paramalgoritmo;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Configuracionsistema getConfiguracionsistema() {
        return this.configuracionsistema;
    }
    
    public void setConfiguracionsistema(Configuracionsistema configuracionsistema) {
        this.configuracionsistema = configuracionsistema;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Double getVelocidadMaxima() {
        return this.velocidadMaxima;
    }
    
    public void setVelocidadMaxima(Double velocidadMaxima) {
        this.velocidadMaxima = velocidadMaxima;
    }
    public String getNombreEjecucion() {
        return this.nombreEjecucion;
    }
    
    public void setNombreEjecucion(String nombreEjecucion) {
        this.nombreEjecucion = nombreEjecucion;
    }
    public Double getVelocidadHistorica() {
        return this.velocidadHistorica;
    }
    
    public void setVelocidadHistorica(Double velocidadHistorica) {
        this.velocidadHistorica = velocidadHistorica;
    }
    public Set getVehiculos() {
        return this.vehiculos;
    }
    
    public void setVehiculos(Set vehiculos) {
        this.vehiculos = vehiculos;
    }
    public Set getEjecucionalgoritmoxsemaforos() {
        return this.ejecucionalgoritmoxsemaforos;
    }
    
    public void setEjecucionalgoritmoxsemaforos(Set ejecucionalgoritmoxsemaforos) {
        this.ejecucionalgoritmoxsemaforos = ejecucionalgoritmoxsemaforos;
    }
    public Set getEjecucionalgoritmoxcuadraxnodos() {
        return this.ejecucionalgoritmoxcuadraxnodos;
    }
    
    public void setEjecucionalgoritmoxcuadraxnodos(Set ejecucionalgoritmoxcuadraxnodos) {
        this.ejecucionalgoritmoxcuadraxnodos = ejecucionalgoritmoxcuadraxnodos;
    }




}


