package pe.edu.pucp.linelight.model;
// Generated 11/06/2014 07:24:50 PM by Hibernate Tools 3.2.1.GA



/**
 * Ejecucionalgoritmoxsemaforo generated by hbm2java
 */
public class Ejecucionalgoritmoxsemaforo  implements java.io.Serializable {


     private EjecucionalgoritmoxsemaforoId id;
     private Ejecucionalgoritmo ejecucionalgoritmo;
     private Integer tverde;
     private Integer trojo;

    public Ejecucionalgoritmoxsemaforo() {
    }

	
    public Ejecucionalgoritmoxsemaforo(EjecucionalgoritmoxsemaforoId id, Ejecucionalgoritmo ejecucionalgoritmo) {
        this.id = id;
        this.ejecucionalgoritmo = ejecucionalgoritmo;
    }
    public Ejecucionalgoritmoxsemaforo(EjecucionalgoritmoxsemaforoId id, Ejecucionalgoritmo ejecucionalgoritmo, Integer tverde, Integer trojo) {
       this.id = id;
       this.ejecucionalgoritmo = ejecucionalgoritmo;
       this.tverde = tverde;
       this.trojo = trojo;
    }
   
    public EjecucionalgoritmoxsemaforoId getId() {
        return this.id;
    }
    
    public void setId(EjecucionalgoritmoxsemaforoId id) {
        this.id = id;
    }
    public Ejecucionalgoritmo getEjecucionalgoritmo() {
        return this.ejecucionalgoritmo;
    }
    
    public void setEjecucionalgoritmo(Ejecucionalgoritmo ejecucionalgoritmo) {
        this.ejecucionalgoritmo = ejecucionalgoritmo;
    }
    public Integer getTverde() {
        return this.tverde;
    }
    
    public void setTverde(Integer tverde) {
        this.tverde = tverde;
    }
    public Integer getTrojo() {
        return this.trojo;
    }
    
    public void setTrojo(Integer trojo) {
        this.trojo = trojo;
    }




}


