package pe.edu.pucp.linelight.model;
// Generated 04/06/2014 09:38:07 PM by Hibernate Tools 3.6.0



/**
 * Ejecucionalgoritmoxcuadraxnodo generated by hbm2java
 */
public class Ejecucionalgoritmoxcuadraxnodo  implements java.io.Serializable {


     private EjecucionalgoritmoxcuadraxnodoId id;
     private Tramoxnodo tramoxnodo;
     private Ejecucionalgoritmo ejecucionalgoritmo;
     private Boolean estadosSemaforo;
     private Boolean estadoCuadra;
     private Integer tverde;
     private Integer trojo;
     private Double velocidadPromParcial;

    public Ejecucionalgoritmoxcuadraxnodo() {
    }

	
    public Ejecucionalgoritmoxcuadraxnodo(EjecucionalgoritmoxcuadraxnodoId id, Tramoxnodo tramoxnodo, Ejecucionalgoritmo ejecucionalgoritmo) {
        this.id = id;
        this.tramoxnodo = tramoxnodo;
        this.ejecucionalgoritmo = ejecucionalgoritmo;
    }
    public Ejecucionalgoritmoxcuadraxnodo(EjecucionalgoritmoxcuadraxnodoId id, Tramoxnodo tramoxnodo, Ejecucionalgoritmo ejecucionalgoritmo, Boolean estadosSemaforo, Boolean estadoCuadra, Integer tverde, Integer trojo, Double velocidadPromParcial) {
       this.id = id;
       this.tramoxnodo = tramoxnodo;
       this.ejecucionalgoritmo = ejecucionalgoritmo;
       this.estadosSemaforo = estadosSemaforo;
       this.estadoCuadra = estadoCuadra;
       this.tverde = tverde;
       this.trojo = trojo;
       this.velocidadPromParcial = velocidadPromParcial;
    }
   
    public EjecucionalgoritmoxcuadraxnodoId getId() {
        return this.id;
    }
    
    public void setId(EjecucionalgoritmoxcuadraxnodoId id) {
        this.id = id;
    }
    public Tramoxnodo getTramoxnodo() {
        return this.tramoxnodo;
    }
    
    public void setTramoxnodo(Tramoxnodo tramoxnodo) {
        this.tramoxnodo = tramoxnodo;
    }
    public Ejecucionalgoritmo getEjecucionalgoritmo() {
        return this.ejecucionalgoritmo;
    }
    
    public void setEjecucionalgoritmo(Ejecucionalgoritmo ejecucionalgoritmo) {
        this.ejecucionalgoritmo = ejecucionalgoritmo;
    }
    public Boolean getEstadosSemaforo() {
        return this.estadosSemaforo;
    }
    
    public void setEstadosSemaforo(Boolean estadosSemaforo) {
        this.estadosSemaforo = estadosSemaforo;
    }
    public Boolean getEstadoCuadra() {
        return this.estadoCuadra;
    }
    
    public void setEstadoCuadra(Boolean estadoCuadra) {
        this.estadoCuadra = estadoCuadra;
    }
    public Integer getTverde() {
        return this.tverde;
    }
    
    public void setTverde(Integer tverde) {
        this.tverde = tverde;
    }
    public Integer getTrojo() {
        return this.trojo;
    }
    
    public void setTrojo(Integer trojo) {
        this.trojo = trojo;
    }
    public Double getVelocidadPromParcial() {
        return this.velocidadPromParcial;
    }
    
    public void setVelocidadPromParcial(Double velocidadPromParcial) {
        this.velocidadPromParcial = velocidadPromParcial;
    }




}


