package pe.edu.pucp.linelight.model;
// Generated 12/06/2014 12:06:23 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Horario generated by hbm2java
 */
public class Horario  implements java.io.Serializable {


     private Integer idHorario;
     private String hora;
     private String dia;
     private Integer probAvenida;
     private Integer probCalle;
     private Set viaxhorarios = new HashSet(0);
     private Set distritoxhorarios = new HashSet(0);
     private Set ejecucionalgoritmos = new HashSet(0);

    public Horario() {
    }

    public Horario(String hora, String dia, Integer probAvenida, Integer probCalle, Set viaxhorarios, Set distritoxhorarios, Set ejecucionalgoritmos) {
       this.hora = hora;
       this.dia = dia;
       this.probAvenida = probAvenida;
       this.probCalle = probCalle;
       this.viaxhorarios = viaxhorarios;
       this.distritoxhorarios = distritoxhorarios;
       this.ejecucionalgoritmos = ejecucionalgoritmos;
    }
   
    public Integer getIdHorario() {
        return this.idHorario;
    }
    
    public void setIdHorario(Integer idHorario) {
        this.idHorario = idHorario;
    }
    public String getHora() {
        return this.hora;
    }
    
    public void setHora(String hora) {
        this.hora = hora;
    }
    public String getDia() {
        return this.dia;
    }
    
    public void setDia(String dia) {
        this.dia = dia;
    }
    public Integer getProbAvenida() {
        return this.probAvenida;
    }
    
    public void setProbAvenida(Integer probAvenida) {
        this.probAvenida = probAvenida;
    }
    public Integer getProbCalle() {
        return this.probCalle;
    }
    
    public void setProbCalle(Integer probCalle) {
        this.probCalle = probCalle;
    }
    public Set getViaxhorarios() {
        return this.viaxhorarios;
    }
    
    public void setViaxhorarios(Set viaxhorarios) {
        this.viaxhorarios = viaxhorarios;
    }
    public Set getDistritoxhorarios() {
        return this.distritoxhorarios;
    }
    
    public void setDistritoxhorarios(Set distritoxhorarios) {
        this.distritoxhorarios = distritoxhorarios;
    }
    public Set getEjecucionalgoritmos() {
        return this.ejecucionalgoritmos;
    }
    
    public void setEjecucionalgoritmos(Set ejecucionalgoritmos) {
        this.ejecucionalgoritmos = ejecucionalgoritmos;
    }




}


