package pe.edu.pucp.linelight.model;
// Generated 11/06/2014 07:24:50 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Paramalgoritmo generated by hbm2java
 */
public class Paramalgoritmo  implements java.io.Serializable {


     private Integer idParamAlgoritmo;
     private int maxTamPoblacion;
     private int maxCicloSinCambiar;
     private double tasaCasamiento;
     private double tasaMutacion;
     private Integer tamPoblacionInicial;
     private Boolean elitismo;
     private Set ejecucionalgoritmos = new HashSet(0);

    public Paramalgoritmo() {
    }

	
    public Paramalgoritmo(int maxTamPoblacion, int maxCicloSinCambiar, double tasaCasamiento, double tasaMutacion) {
        this.maxTamPoblacion = maxTamPoblacion;
        this.maxCicloSinCambiar = maxCicloSinCambiar;
        this.tasaCasamiento = tasaCasamiento;
        this.tasaMutacion = tasaMutacion;
    }
    public Paramalgoritmo(int maxTamPoblacion, int maxCicloSinCambiar, double tasaCasamiento, double tasaMutacion, Integer tamPoblacionInicial, Boolean elitismo, Set ejecucionalgoritmos) {
       this.maxTamPoblacion = maxTamPoblacion;
       this.maxCicloSinCambiar = maxCicloSinCambiar;
       this.tasaCasamiento = tasaCasamiento;
       this.tasaMutacion = tasaMutacion;
       this.tamPoblacionInicial = tamPoblacionInicial;
       this.elitismo = elitismo;
       this.ejecucionalgoritmos = ejecucionalgoritmos;
    }
   
    public Integer getIdParamAlgoritmo() {
        return this.idParamAlgoritmo;
    }
    
    public void setIdParamAlgoritmo(Integer idParamAlgoritmo) {
        this.idParamAlgoritmo = idParamAlgoritmo;
    }
    public int getMaxTamPoblacion() {
        return this.maxTamPoblacion;
    }
    
    public void setMaxTamPoblacion(int maxTamPoblacion) {
        this.maxTamPoblacion = maxTamPoblacion;
    }
    public int getMaxCicloSinCambiar() {
        return this.maxCicloSinCambiar;
    }
    
    public void setMaxCicloSinCambiar(int maxCicloSinCambiar) {
        this.maxCicloSinCambiar = maxCicloSinCambiar;
    }
    public double getTasaCasamiento() {
        return this.tasaCasamiento;
    }
    
    public void setTasaCasamiento(double tasaCasamiento) {
        this.tasaCasamiento = tasaCasamiento;
    }
    public double getTasaMutacion() {
        return this.tasaMutacion;
    }
    
    public void setTasaMutacion(double tasaMutacion) {
        this.tasaMutacion = tasaMutacion;
    }
    public Integer getTamPoblacionInicial() {
        return this.tamPoblacionInicial;
    }
    
    public void setTamPoblacionInicial(Integer tamPoblacionInicial) {
        this.tamPoblacionInicial = tamPoblacionInicial;
    }
    public Boolean getElitismo() {
        return this.elitismo;
    }
    
    public void setElitismo(Boolean elitismo) {
        this.elitismo = elitismo;
    }
    public Set getEjecucionalgoritmos() {
        return this.ejecucionalgoritmos;
    }
    
    public void setEjecucionalgoritmos(Set ejecucionalgoritmos) {
        this.ejecucionalgoritmos = ejecucionalgoritmos;
    }




}


