package pe.edu.pucp.linelight.model;
// Generated 03/06/2014 08:23:06 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Perfil generated by hbm2java
 */
public class Perfil  implements java.io.Serializable {


     private Integer idPerfil;
     private String descripcion;
     private Integer estado;
     private String nombre;
     private Integer estadobd;
     private Set menus = new HashSet(0);
     private Set usuarios = new HashSet(0);

    public Perfil() {
    }

    public Perfil(String descripcion, Integer estado, String nombre, Integer estadobd, Set menus, Set usuarios) {
       this.descripcion = descripcion;
       this.estado = estado;
       this.nombre = nombre;
       this.estadobd = estadobd;
       this.menus = menus;
       this.usuarios = usuarios;
    }
   
    public Integer getIdPerfil() {
        return this.idPerfil;
    }
    
    public void setIdPerfil(Integer idPerfil) {
        this.idPerfil = idPerfil;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getEstadobd() {
        return this.estadobd;
    }
    
    public void setEstadobd(Integer estadobd) {
        this.estadobd = estadobd;
    }
    public Set getMenus() {
        return this.menus;
    }
    
    public void setMenus(Set menus) {
        this.menus = menus;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


