package pe.edu.pucp.linelight.model;
// Generated 04/06/2014 09:38:07 PM by Hibernate Tools 3.6.0



/**
 * SemaforoId generated by hbm2java
 */
public class SemaforoId  implements java.io.Serializable {


     private int idSemaforo;
     private long idNodo;

    public SemaforoId() {
    }

    public SemaforoId(int idSemaforo, long idNodo) {
       this.idSemaforo = idSemaforo;
       this.idNodo = idNodo;
    }
   
    public int getIdSemaforo() {
        return this.idSemaforo;
    }
    
    public void setIdSemaforo(int idSemaforo) {
        this.idSemaforo = idSemaforo;
    }
    public long getIdNodo() {
        return this.idNodo;
    }
    
    public void setIdNodo(long idNodo) {
        this.idNodo = idNodo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SemaforoId) ) return false;
		 SemaforoId castOther = ( SemaforoId ) other; 
         
		 return (this.getIdSemaforo()==castOther.getIdSemaforo())
 && (this.getIdNodo()==castOther.getIdNodo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdSemaforo();
         result = 37 * result + (int) this.getIdNodo();
         return result;
   }   


}


