package pe.edu.pucp.linelight.model;
// Generated 12/06/2014 12:06:23 AM by Hibernate Tools 3.6.0



/**
 * SemaforoId generated by hbm2java
 */
public class SemaforoId  implements java.io.Serializable {


     private long idSemaforo;
     private long idNodo;
     private int idDistrito;

    public SemaforoId() {
    }

    public SemaforoId(long idSemaforo, long idNodo, int idDistrito) {
       this.idSemaforo = idSemaforo;
       this.idNodo = idNodo;
       this.idDistrito = idDistrito;
    }
   
    public long getIdSemaforo() {
        return this.idSemaforo;
    }
    
    public void setIdSemaforo(long idSemaforo) {
        this.idSemaforo = idSemaforo;
    }
    public long getIdNodo() {
        return this.idNodo;
    }
    
    public void setIdNodo(long idNodo) {
        this.idNodo = idNodo;
    }
    public int getIdDistrito() {
        return this.idDistrito;
    }
    
    public void setIdDistrito(int idDistrito) {
        this.idDistrito = idDistrito;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SemaforoId) ) return false;
		 SemaforoId castOther = ( SemaforoId ) other; 
         
		 return (this.getIdSemaforo()==castOther.getIdSemaforo())
 && (this.getIdNodo()==castOther.getIdNodo())
 && (this.getIdDistrito()==castOther.getIdDistrito());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getIdSemaforo();
         result = 37 * result + (int) this.getIdNodo();
         result = 37 * result + this.getIdDistrito();
         return result;
   }   


}


