package pe.edu.pucp.linelight.model;
// Generated 12/06/2014 12:06:23 AM by Hibernate Tools 3.6.0



/**
 * TramoxincidenciaId generated by hbm2java
 */
public class TramoxincidenciaId  implements java.io.Serializable {


     private int idIncidencia;
     private int idTramo;
     private int idDistrito;
     private long idVia;

    public TramoxincidenciaId() {
    }

    public TramoxincidenciaId(int idIncidencia, int idTramo, int idDistrito, long idVia) {
       this.idIncidencia = idIncidencia;
       this.idTramo = idTramo;
       this.idDistrito = idDistrito;
       this.idVia = idVia;
    }
   
    public int getIdIncidencia() {
        return this.idIncidencia;
    }
    
    public void setIdIncidencia(int idIncidencia) {
        this.idIncidencia = idIncidencia;
    }
    public int getIdTramo() {
        return this.idTramo;
    }
    
    public void setIdTramo(int idTramo) {
        this.idTramo = idTramo;
    }
    public int getIdDistrito() {
        return this.idDistrito;
    }
    
    public void setIdDistrito(int idDistrito) {
        this.idDistrito = idDistrito;
    }
    public long getIdVia() {
        return this.idVia;
    }
    
    public void setIdVia(long idVia) {
        this.idVia = idVia;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TramoxincidenciaId) ) return false;
		 TramoxincidenciaId castOther = ( TramoxincidenciaId ) other; 
         
		 return (this.getIdIncidencia()==castOther.getIdIncidencia())
 && (this.getIdTramo()==castOther.getIdTramo())
 && (this.getIdDistrito()==castOther.getIdDistrito())
 && (this.getIdVia()==castOther.getIdVia());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdIncidencia();
         result = 37 * result + this.getIdTramo();
         result = 37 * result + this.getIdDistrito();
         result = 37 * result + (int) this.getIdVia();
         return result;
   }   


}


