package pe.edu.pucp.linelight.model;
// Generated 12/06/2014 12:06:23 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String idUsuario;
     private Perfil perfil;
     private String nombre;
     private String app;
     private String apm;
     private String password;
     private String correo;
     private String dni;
     private Date fechaNac;
     private String telefono;
     private String celular;
     private String direccion;
     private Integer estado;
     private Integer estadobd;
     private int primerAcceso;
     private Set usuarioxaccions = new HashSet(0);
     private Set ejecucionalgoritmos = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String idUsuario, Perfil perfil, String nombre, String app, String apm, String password, Date fechaNac, int primerAcceso) {
        this.idUsuario = idUsuario;
        this.perfil = perfil;
        this.nombre = nombre;
        this.app = app;
        this.apm = apm;
        this.password = password;
        this.fechaNac = fechaNac;
        this.primerAcceso = primerAcceso;
    }
    public Usuario(String idUsuario, Perfil perfil, String nombre, String app, String apm, String password, String correo, String dni, Date fechaNac, String telefono, String celular, String direccion, Integer estado, Integer estadobd, int primerAcceso, Set usuarioxaccions, Set ejecucionalgoritmos) {
       this.idUsuario = idUsuario;
       this.perfil = perfil;
       this.nombre = nombre;
       this.app = app;
       this.apm = apm;
       this.password = password;
       this.correo = correo;
       this.dni = dni;
       this.fechaNac = fechaNac;
       this.telefono = telefono;
       this.celular = celular;
       this.direccion = direccion;
       this.estado = estado;
       this.estadobd = estadobd;
       this.primerAcceso = primerAcceso;
       this.usuarioxaccions = usuarioxaccions;
       this.ejecucionalgoritmos = ejecucionalgoritmos;
    }
   
    public String getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Perfil getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApp() {
        return this.app;
    }
    
    public void setApp(String app) {
        this.app = app;
    }
    public String getApm() {
        return this.apm;
    }
    
    public void setApm(String apm) {
        this.apm = apm;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }
    public Integer getEstadobd() {
        return this.estadobd;
    }
    
    public void setEstadobd(Integer estadobd) {
        this.estadobd = estadobd;
    }
    public int getPrimerAcceso() {
        return this.primerAcceso;
    }
    
    public void setPrimerAcceso(int primerAcceso) {
        this.primerAcceso = primerAcceso;
    }
    public Set getUsuarioxaccions() {
        return this.usuarioxaccions;
    }
    
    public void setUsuarioxaccions(Set usuarioxaccions) {
        this.usuarioxaccions = usuarioxaccions;
    }
    public Set getEjecucionalgoritmos() {
        return this.ejecucionalgoritmos;
    }
    
    public void setEjecucionalgoritmos(Set ejecucionalgoritmos) {
        this.ejecucionalgoritmos = ejecucionalgoritmos;
    }




}


