package pe.edu.pucp.linelight.model;
// Generated 12/06/2014 12:06:23 AM by Hibernate Tools 3.6.0



/**
 * UsuarioxaccionId generated by hbm2java
 */
public class UsuarioxaccionId  implements java.io.Serializable {


     private int idAccion;
     private String idUsuario;
     private int id;

    public UsuarioxaccionId() {
    }

    public UsuarioxaccionId(int idAccion, String idUsuario) {
       this.idAccion = idAccion;
       this.idUsuario = idUsuario;
    }
   
    public int getIdAccion() {
        return this.idAccion;
    }
    
    public void setIdAccion(int idAccion) {
        this.idAccion = idAccion;
    }
    public String getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsuarioxaccionId) ) return false;
		 UsuarioxaccionId castOther = ( UsuarioxaccionId ) other; 
         
		 return (this.getIdAccion()==castOther.getIdAccion())
 && ( (this.getIdUsuario()==castOther.getIdUsuario()) || ( this.getIdUsuario()!=null && castOther.getIdUsuario()!=null && this.getIdUsuario().equals(castOther.getIdUsuario()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdAccion();
         result = 37 * result + ( getIdUsuario() == null ? 0 : this.getIdUsuario().hashCode() );
         return result;
   }   


}


