package pe.edu.pucp.linelight.model;
// Generated 14-jun-2014 23:39:46 by Hibernate Tools 3.6.0



/**
 * Usuarioxaccion generated by hbm2java
 */
public class Usuarioxaccion  implements java.io.Serializable {


     private UsuarioxaccionId id;
     private Usuario usuario;
     private Accion accion;
     private String ip;
     private String tabla;

    public Usuarioxaccion() {
    }

	
    public Usuarioxaccion(UsuarioxaccionId id, Usuario usuario, Accion accion) {
        this.id = id;
        this.usuario = usuario;
        this.accion = accion;
    }
    public Usuarioxaccion(UsuarioxaccionId id, Usuario usuario, Accion accion, String ip, String tabla) {
       this.id = id;
       this.usuario = usuario;
       this.accion = accion;
       this.ip = ip;
       this.tabla = tabla;
    }
   
    public UsuarioxaccionId getId() {
        return this.id;
    }
    
    public void setId(UsuarioxaccionId id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Accion getAccion() {
        return this.accion;
    }
    
    public void setAccion(Accion accion) {
        this.accion = accion;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public String getTabla() {
        return this.tabla;
    }
    
    public void setTabla(String tabla) {
        this.tabla = tabla;
    }




}


