package pe.edu.pucp.linelight.model;
// Generated 14-jun-2014 23:39:46 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * UsuarioxaccionId generated by hbm2java
 */
public class UsuarioxaccionId  implements java.io.Serializable {


     private int idAccion;
     private String idUsuario;
     private Date fecha;
     private int idUsuarioxAccion;

    public UsuarioxaccionId() {
    }

    public UsuarioxaccionId(int idAccion, String idUsuario, Date fecha, int idUsuarioxAccion) {
       this.idAccion = idAccion;
       this.idUsuario = idUsuario;
       this.fecha = fecha;
       this.idUsuarioxAccion = idUsuarioxAccion;
    }
   
    public int getIdAccion() {
        return this.idAccion;
    }
    
    public void setIdAccion(int idAccion) {
        this.idAccion = idAccion;
    }
    public String getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public int getIdUsuarioxAccion() {
        return this.idUsuarioxAccion;
    }
    
    public void setIdUsuarioxAccion(int idUsuarioxAccion) {
        this.idUsuarioxAccion = idUsuarioxAccion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsuarioxaccionId) ) return false;
		 UsuarioxaccionId castOther = ( UsuarioxaccionId ) other; 
         
		 return (this.getIdAccion()==castOther.getIdAccion())
 && ( (this.getIdUsuario()==castOther.getIdUsuario()) || ( this.getIdUsuario()!=null && castOther.getIdUsuario()!=null && this.getIdUsuario().equals(castOther.getIdUsuario()) ) )
 && ( (this.getFecha()==castOther.getFecha()) || ( this.getFecha()!=null && castOther.getFecha()!=null && this.getFecha().equals(castOther.getFecha()) ) )
 && (this.getIdUsuarioxAccion()==castOther.getIdUsuarioxAccion());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdAccion();
         result = 37 * result + ( getIdUsuario() == null ? 0 : this.getIdUsuario().hashCode() );
         result = 37 * result + ( getFecha() == null ? 0 : this.getFecha().hashCode() );
         result = 37 * result + this.getIdUsuarioxAccion();
         return result;
   }   


}


