package pe.edu.pucp.linelight.model;
// Generated 11/06/2014 07:24:50 PM by Hibernate Tools 3.2.1.GA



/**
 * Viaxhorario generated by hbm2java
 */
public class Viaxhorario  implements java.io.Serializable {


     private ViaxhorarioId id;
     private Horario horario;
     private Via via;
     private Integer numCarros;

    public Viaxhorario() {
    }

	
    public Viaxhorario(ViaxhorarioId id, Horario horario, Via via) {
        this.id = id;
        this.horario = horario;
        this.via = via;
    }
    public Viaxhorario(ViaxhorarioId id, Horario horario, Via via, Integer numCarros) {
       this.id = id;
       this.horario = horario;
       this.via = via;
       this.numCarros = numCarros;
    }
   
    public ViaxhorarioId getId() {
        return this.id;
    }
    
    public void setId(ViaxhorarioId id) {
        this.id = id;
    }
    public Horario getHorario() {
        return this.horario;
    }
    
    public void setHorario(Horario horario) {
        this.horario = horario;
    }
    public Via getVia() {
        return this.via;
    }
    
    public void setVia(Via via) {
        this.via = via;
    }
    public Integer getNumCarros() {
        return this.numCarros;
    }
    
    public void setNumCarros(Integer numCarros) {
        this.numCarros = numCarros;
    }




}


