package pe.edu.pucp.linelight.model;
// Generated 11/06/2014 07:24:50 PM by Hibernate Tools 3.2.1.GA



/**
 * ViaxhorarioId generated by hbm2java
 */
public class ViaxhorarioId  implements java.io.Serializable {


     private int idHorario;
     private int idDistrito;
     private long idVia;

    public ViaxhorarioId() {
    }

    public ViaxhorarioId(int idHorario, int idDistrito, long idVia) {
       this.idHorario = idHorario;
       this.idDistrito = idDistrito;
       this.idVia = idVia;
    }
   
    public int getIdHorario() {
        return this.idHorario;
    }
    
    public void setIdHorario(int idHorario) {
        this.idHorario = idHorario;
    }
    public int getIdDistrito() {
        return this.idDistrito;
    }
    
    public void setIdDistrito(int idDistrito) {
        this.idDistrito = idDistrito;
    }
    public long getIdVia() {
        return this.idVia;
    }
    
    public void setIdVia(long idVia) {
        this.idVia = idVia;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ViaxhorarioId) ) return false;
		 ViaxhorarioId castOther = ( ViaxhorarioId ) other; 
         
		 return (this.getIdHorario()==castOther.getIdHorario())
 && (this.getIdDistrito()==castOther.getIdDistrito())
 && (this.getIdVia()==castOther.getIdVia());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdHorario();
         result = 37 * result + this.getIdDistrito();
         result = 37 * result + (int) this.getIdVia();
         return result;
   }   


}


